insert into authors (id, photo, slug, name, description) values (23654, 'http://dummyimage.com/605x175.png/ff4444/ffffff', 'author-aut-999', 'Author Tester', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.');

insert into books (id, pub_date, is_bestseller, slug, title, image, description, price, discount) values (4001, '2021-06-03', 1, 'book-aaa-003', 'Southern Comfort', 'http://dummyimage.com/265x289.png/5fa2dd/ffffff', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 388, 0.19);
insert into books (id, pub_date, is_bestseller, slug, title, image, description, price, discount) values (4002, '2021-06-20', 1, 'book-sss-265', 'Africa: Texas Style', 'http://dummyimage.com/621x312.png/cc0000/ffffff', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.', 1980, 0.37);
insert into books (id, pub_date, is_bestseller, slug, title, image, description, price, discount) values (4003, '2021-04-10', 0, 'book-kgg-452', 'Bobcat Goldthwait: You Don''t Look the Same Either', 'http://dummyimage.com/611x405.png/ff4444/ffffff', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 428, 0.41);
insert into books (id, pub_date, is_bestseller, slug, title, image, description, price, discount) values (4004, '2021-04-19', 1, 'book-rrr-552', 'Taxi Blues', 'http://dummyimage.com/449x715.png/dddddd/000000', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 703, 0.39);
insert into books (id, pub_date, is_bestseller, slug, title, image, description, price, discount) values (4005, '2020-07-26', 0, 'book-jjj-460', 'Arsène Lupin Returns', 'http://dummyimage.com/265x296.png/dddddd/000000', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 2978, 0.36);
insert into books (id, pub_date, is_bestseller, slug, title, image, description, price, discount) values (4006, '2020-12-25', 0, 'book-vbb-199', 'Music Never Stopped, The', 'http://dummyimage.com/697x533.png/cc0000/ffffff', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', 2282, 0.14);
insert into books (id, pub_date, is_bestseller, slug, title, image, description, price, discount) values (4007, '2020-09-07', 1, 'book-yui-490', 'The Baby Maker', 'http://dummyimage.com/298x615.png/5fa2dd/ffffff', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 1839, 0.31);
insert into books (id, pub_date, is_bestseller, slug, title, image, description, price, discount) values (4008, '2020-08-14', 1, 'book-cdv-230', 'Queen of Versailles, The', 'http://dummyimage.com/321x428.png/5fa2dd/ffffff', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', 1845, 0.3);
insert into books (id, pub_date, is_bestseller, slug, title, image, description, price, discount) values (4009, '2020-12-13', 1, 'book-mmm-191', 'Assassination on the Tiber', 'http://dummyimage.com/751x731.png/cc0000/ffffff', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 1942, 0.45);
insert into books (id, pub_date, is_bestseller, slug, title, image, description, price, discount) values (4010, '2020-12-26', 0, 'book-ooo-749', 'Reality of Love, The (I Want to Marry Ryan Banks)', 'http://dummyimage.com/506x652.png/cc0000/ffffff', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.', 2491, 0.43);

insert into book2author (id, book_id, author_id, sort_index) values (7001, 4001, 23654, 0);
insert into book2author (id, book_id, author_id, sort_index) values (7002, 4002, 23654, 0);
insert into book2author (id, book_id, author_id, sort_index) values (7003, 4003, 23654, 0);
insert into book2author (id, book_id, author_id, sort_index) values (7004, 4004, 23654, 0);
insert into book2author (id, book_id, author_id, sort_index) values (7005, 4005, 23654, 0);
insert into book2author (id, book_id, author_id, sort_index) values (7006, 4006, 23654, 0);
insert into book2author (id, book_id, author_id, sort_index) values (7007, 4007, 23654, 1);
insert into book2author (id, book_id, author_id, sort_index) values (7008, 4008, 23654, 0);
insert into book2author (id, book_id, author_id, sort_index) values (7009, 4009, 23654, 1);
insert into book2author (id, book_id, author_id, sort_index) values (7010, 4010, 23654, 0);