insert into tags (id, name) values (1, 'Horde');
insert into tags (id, name) values (2, 'Iron Eagle IV');
insert into tags (id, name) values (3, 'Adjust Your Tracking');
insert into tags (id, name) values (4, 'Afternoon of a Torturer');
insert into tags (id, name) values (5, 'Hands of Fate');
insert into tags (id, name) values (6, 'Hit Squad');
insert into tags (id, name) values (7, 'Thunderbolt');
insert into tags (id, name) values (8, 'Monster Slayer');
insert into tags (id, name) values (9, '50 First Dates');
insert into tags (id, name) values (10, 'Place Called Chiapas');
insert into tags (id, name) values (11, 'Kill, Baby, Kill ');
insert into tags (id, name) values (12, 'Flash Gordon');
insert into tags (id, name) values (13, 'Long Goodbye');
insert into tags (id, name) values (14, 'Buffalo Soldiers');
insert into tags (id, name) values (15, 'Willard');
insert into tags (id, name) values (16, 'The Smoking Gun');
insert into tags (id, name) values (17, 'Little Mermaid');
insert into tags (id, name) values (18, '48 Shades');
insert into tags (id, name) values (19, 'National Lampoon');
insert into tags (id, name) values (20, 'Nico and Dani');
insert into tags (id, name) values (21, 'Tokyo');
insert into tags (id, name) values (22, 'Who Lives at Home');
insert into tags (id, name) values (23, 'Space Raiders');
insert into tags (id, name) values (24, 'Experiment Perilous');
insert into tags (id, name) values (25, 'Under Fire');
insert into tags (id, name) values (26, 'Lightning Bug');
insert into tags (id, name) values (27, 'Dead or Alive');
insert into tags (id, name) values (28, 'Injury to One');
insert into tags (id, name) values (29, 'Wild Rovers');
insert into tags (id, name) values (30, 'll Cry Tomorrow');
insert into tags (id, name) values (31, 'Get Hard');
insert into tags (id, name) values (32, 'Princess');
insert into tags (id, name) values (33, 'Belle of the Nineties');
insert into tags (id, name) values (34, 'Beast of Yucca Flats');
insert into tags (id, name) values (35, 'Welcome to Macintosh');
insert into tags (id, name) values (36, 'Over Your Dead Body');
insert into tags (id, name) values (37, 'Dr. Dolittle');
insert into tags (id, name) values (38, 'Irina Palm');
insert into tags (id, name) values (39, 'Bell Boy');
insert into tags (id, name) values (40, 'Last Stop for Paul');

